apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor-container
        image: marcusvj/monitor-pod:latest
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
          - name: REDIS_HOST
            value: "redis-service"