apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: replicaset-manager-role
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: replicaset-manager-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: monitor-sa
  namespace: default
roleRef:
  kind: Role
  name: replicaset-manager-role
  apiGroup: rbac.authorization.k8s.io